version: "3.3"
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=mini_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  db-data:
